Add max_charge parameter to set_operation_mode for ET class
marcelblijleven/goodwe pull request #14
Opened 2022-06-08 13:36 UTC by adamb314

This pull request is for fixing a bug when using `set_operation_mode` with `operation_mode = 4` on an ET inverter.

On ET inverters there is an extra eco mode parameter for maximum charge. This parameter is sometimes set to 0, when using the current version of this lib, resulting in the inverter not charging.
To fix this issue I implemented `EcoModeV2` which handles this `max_charge` parameter and added this to the ET implementation:
`inverter.set_operation_mode(4, power, max_charge)`.

The default value of `max_charge` is set to 100 so that:
`inverter.set_operation_mode(4, power)`
works as expected.

The device info for the inverter I have tested the new code on is:
```
modbus_version = 1
rated_power = 10000
ac_output_type = 254
model_name = 'GW10K-ET'
dsp1_sw_version = 8
dsp2_sw_version = 8
dsp_svn_version = 159
arm_sw_version = 19
arm_svn_version = 207
software_version = '04029-08-S11'
arm_version = '02041-19-S00'
```

2022-07-06 19:24 UTC, mletenay requested changes

2022-07-07 16:49 UTC, adamb314 commented on goodwe/sensor.py
> +        if max_charge < 0 or end_m > 100:
Yes, the inverter I have tested on has an additional set of registers:
```
EcoModeV2_1 @ 47547:
    2b: start
    2b: end
    2b: day_of_week
    2b: power
    2b: maxCharge
    2b: _padding_
EcoModeV2_2 @ 47553:
    2b: start
    2b: end
    2b: day_of_week
    2b: power
    2b: maxCharge
    2b: _padding_
EcoModeV2_3 @ 47559:
    2b: start
    2b: end
    2b: day_of_week
    2b: power
    2b: maxCharge
    2b: _padding_
EcoModeV2_4 @ 47565:
    2b: start
    2b: end
    2b: day_of_week
    2b: power
    2b: maxCharge
    2b: _padding_
```

The old registers:
```
EcoMode_1 @ 47515:
    2b: start
    2b: end
    2b: power
    2b: dayOfWeek
EcoMode_2 @ 47519:
    2b: start
    2b: end
    2b: power
    2b: dayOfWeek
EcoMode_3 @ 47523:
    2b: start
    2b: end
    2b: power
    2b: dayOfWeek
EcoMode_4 @ 47527:
    2b: start
    2b: end
    2b: power
    2b: dayOfWeek
```

still work most of the time, but then you cannot set the maxCharge parameter. This parameter is present in the SEMS "PV Master" app. Without this fix I had to open the SEMS "PV Master" app and set max charge to 100% to get the battery to start charging as configured.

2022-07-12 19:58 UTC, mletenay commented on goodwe/sensor.py
> +        if max_charge < 0 or end_m > 100:
Aaah, I see ! 
I did not notice those are new modbus registers, it makes sense now.
The question is now, how to figure out when to use which version/registers.

2022-07-24 17:18 UTC, adamb314 commented
I added the _supports_eco_mode_v2 function to handle when to use the EcoModeV2 registers or not. Do you think:
```
if self.dsp1_sw_version < 8:
    return False
if self.dsp2_sw_version < 8:
    return False
if self.arm_sw_version < 19:
    return False
return True
```
is the correct check?

I only have one inverter to test on so I cannot say...

2022-08-09 11:59 UTC, mletenay approved these changes

2022-08-09 11:59 UTC, merged